// ClipClass PDF Compilation Engine using pdfkit
import PDFDocument from 'pdfkit';

/**
 * Helper to draw a dashed or solid line in PDFKit
 */
function drawHorizontalDivider(doc, y, color = '#E2E8F0', width = 1) {
  doc.moveTo(50, y)
     .lineTo(562, y)
     .lineWidth(width)
     .stroke(color);
}

/**
 * Helper to draw empty student answer lines
 */
function drawStudentAnswerLines(doc, y, count = 4) {
  doc.save();
  doc.lineWidth(0.5);
  doc.strokeColor('#94A3B8');
  doc.dash(3, { space: 3 });
  
  let currentY = y;
  for (let i = 0; i < count; i++) {
    currentY += 24;
    doc.moveTo(50, currentY)
       .lineTo(562, currentY)
       .stroke();
  }
  doc.restore();
  return currentY;
}

/**
 * Dynamic PDF builder using HSL-equivalent design tokens.
 * Compiles and returns a binary PDF Buffer.
 * 
 * @param {Object} data - The structured JSON payload generated by the AI
 * @param {Object} meta - Video metadata details (videoId, videoTitle, channelName, ageGroup, etc.)
 */
export async function compileWorkbookPDF(data, meta) {
  return new Promise((resolve, reject) => {
    try {
      // Standard Letter size: 612 x 792 points. Page margins: 50pt
      // Available printable width = 612 - 100 = 512 points
      const doc = new PDFDocument({ 
        size: 'LETTER', 
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        bufferPages: true 
      });

      const buffers = [];
      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', err => reject(err));

      // ==========================================
      // PAGE 1: STUDENT WORKSHEET
      // ==========================================
      
      // Top colored accent bar (Coral Glow #FF4B2B equivalent)
      doc.rect(50, 40, 512, 4).fill('#FF4B2B');

      // Top Header Label
      doc.fillColor('#FF4B2B')
         .font('Helvetica-Bold')
         .fontSize(8)
         .text('CLIPCLASS STUDIO  |  STUDENT WORKBOOK', 50, 55, { characterSpacing: 1 });

      // Clean Naming: [Topic/Video Title] | Student Workbook
      const studentTitle = `${meta.videoTitle} | Student Workbook`;
      doc.fillColor('#0F172A')
         .font('Helvetica-Bold')
         .fontSize(15)
         .text(studentTitle, 50, 72, { width: 512, align: 'left' });

      // SECONDARY DETAILS REMOVED as requested:
      // Completely removed: "Created by: YouTube Creator" and "Target Level: Ages X-XX"

      // Student input fields
      let yPos = doc.y + 14;
      doc.fillColor('#0F172A')
         .font('Helvetica-Bold')
         .fontSize(9.5)
         .text('Student Name: ', 50, yPos);
         
      // Draw standard input underline
      doc.moveTo(125, yPos + 8).lineTo(300, yPos + 8).lineWidth(1).strokeColor('#64748B').stroke();
      
      doc.text('Date: ', 315, yPos);
      doc.moveTo(345, yPos + 8).lineTo(440, yPos + 8).stroke();
      
      doc.text('Class: ', 455, yPos);
      doc.moveTo(490, yPos + 8).lineTo(562, yPos + 8).stroke();

      yPos += 20;
      drawHorizontalDivider(doc, yPos, '#E2E8F0', 1);

      // SECTION 1: SUMMARY (Renamed from EXECUTIVE SUMMARY)
      yPos += 15;
      doc.fillColor('#1E293B')
         .font('Helvetica-Bold')
         .fontSize(11)
         .text('Summary', 50, yPos);

      yPos = doc.y + 6;
      doc.fillColor('#334155')
         .font('Helvetica')
         .fontSize(9.5)
         .lineGap(3)
         .text(data.summary, 50, yPos, { width: 512, align: 'justify' });

      yPos = doc.y + 15;

      // SECTION 2: QUESTIONS (Renamed from ACTIVE-LISTENING TIMELINE CHALLENGE)
      doc.fillColor('#1E293B')
         .font('Helvetica-Bold')
         .fontSize(11)
         .text('Questions', 50, yPos);

      yPos = doc.y + 12;

      // Draw chronological questions without timestamps
      data.questions.forEach((q, idx) => {
        // Prevent layout collision or running off page by checking heights
        // Budgeting for 4 lines of answers (roughly 100 points of vertical space)
        if (yPos > 600) {
          doc.addPage();
          doc.rect(50, 40, 512, 4).fill('#FF4B2B');
          yPos = 60;
        }

        doc.fillColor('#1E293B')
           .font('Helvetica-Bold')
           .fontSize(9.5)
           .text(`Q${idx + 1}.`, 50, yPos);

        // Completely removed chronological timestamps [MM:SS] from student question drawing block

        doc.fillColor('#334155')
           .font('Helvetica')
           .text(q.question, 80, yPos, { width: 482 }); // Restructured wider width layout

        yPos = doc.y + 4;
        
        // Student Workbook: Write-in section contains exactly four empty lines of space
        yPos = drawStudentAnswerLines(doc, yPos, 4);
        yPos += 18;
      });


      // ==========================================
      // PAGE 2: TEACHER ANSWER KEY (Strictly Decoupled)
      // ==========================================
      doc.addPage();

      // Top colored accent bar (Crimson Red #EF4444 equivalent)
      doc.rect(50, 40, 512, 4).fill('#EF4444');

      // Top Header Label
      doc.fillColor('#EF4444')
         .font('Helvetica-Bold')
         .fontSize(8)
         .text('CLIPCLASS STUDIO  |  TEACHER ANSWER KEY (CONFIDENTIAL)', 50, 55, { characterSpacing: 1 });

      // Clean Naming: [Topic/Video Title] | Teacher Answer Key
      const teacherTitle = `${meta.videoTitle} | Teacher Answer Key`;
      doc.fillColor('#0F172A')
         .font('Helvetica-Bold')
         .fontSize(15)
         .text(teacherTitle, 50, 72, { width: 512, align: 'left' });

      // SECONDARY DETAILS REMOVED as requested:
      // Completely removed: "Video Ref: Title • Ages X-XX"

      let teacherY = doc.y + 14;
      drawHorizontalDivider(doc, teacherY, '#F1F5F9', 1.5);
      
      teacherY += 15;

      // Summary Block for Teacher (Renamed to Summary)
      doc.fillColor('#1E293B')
         .font('Helvetica-Bold')
         .fontSize(10.5)
         .text('Summary:', 50, teacherY);

      doc.fillColor('#475569')
         .font('Helvetica')
         .fontSize(9)
         .text(data.summary, 50, doc.y + 4, { width: 512, align: 'justify' });

      teacherY = doc.y + 16;

      // Timed Solutions Section (Renamed to Questions)
      doc.fillColor('#1E293B')
         .font('Helvetica-Bold')
         .fontSize(10.5)
         .text('Questions:', 50, teacherY);

      teacherY = doc.y + 10;

      data.teacherAnswers.forEach((ans, idx) => {
        if (teacherY > 680) {
          doc.addPage();
          doc.rect(50, 40, 512, 4).fill('#EF4444');
          teacherY = 60;
        }

        // Question header - Timestamps [MM:SS] completely stripped
        doc.fillColor('#0F172A')
           .font('Helvetica-Bold')
           .fontSize(9.5)
           .text(`Q${idx + 1}.`, 50, teacherY);

        doc.fillColor('#475569')
           .font('Helvetica')
           .text(ans.question, 80, teacherY, { width: 482 });

        teacherY = doc.y + 5;

        // Model Answer block - Clean Answer formatting section underneath, no lines
        doc.fillColor('#0F172A')
           .font('Helvetica-Bold')
           .fontSize(9.5)
           .text('Answer: ', 80, teacherY, { continued: true });

        doc.fillColor('#334155')
           .font('Helvetica')
           .text(ans.answer, { width: 402, align: 'justify' });

        teacherY = doc.y + 14;
      });


      // ==========================================
      // PAGE 3: GAMIFIED CLASSROOM TRIVIA (If Enabled)
      // ==========================================
      if (meta.gamifiedTrivia && data.triviaScript && data.triviaScript.rounds && data.triviaScript.rounds.length > 0) {
        doc.addPage();

        // Top colored accent bar (Indigo Blue #4F46E5 equivalent)
        doc.rect(50, 40, 512, 4).fill('#4F46E5');

        // Top Header Label
        doc.fillColor('#4F46E5')
           .font('Helvetica-Bold')
           .fontSize(8)
           .text('CLIPCLASS STUDIO  |  GAMIFIED CLASSROOM TRIVIA SCRIPT', 50, 55, { characterSpacing: 1 });

        // Title
        doc.fillColor('#0F172A')
           .font('Helvetica-Bold')
           .fontSize(15)
           .text(data.triviaScript.gameTitle || 'Active Review Trivia Challenge', 50, 72);

        // Instruction block for the game
        doc.fillColor('#4F46E5')
           .font('Helvetica-Bold')
           .fontSize(9.5)
           .text('Host Instructions for Teachers:', 50, doc.y + 8);

        doc.fillColor('#475569')
           .font('Helvetica-Oblique')
           .fontSize(9)
           .text(data.triviaScript.instructions || 'Split the class into competing teams. Ask each question aloud, allowing 30 seconds for groups to deliberate and submit written selections.', 50, doc.y + 4, { width: 512 });

        let triviaY = doc.y + 14;
        drawHorizontalDivider(doc, triviaY, '#E2E8F0', 1);

        triviaY += 15;

        // Loop through trivia rounds
        data.triviaScript.rounds.forEach((round, idx) => {
          if (triviaY > 670) {
            doc.addPage();
            doc.rect(50, 40, 512, 4).fill('#4F46E5');
            triviaY = 60;
          }

          // Question header
          doc.fillColor('#0F172A')
             .font('Helvetica-Bold')
             .fontSize(10)
             .text(`ROUND ${idx + 1}: ${round.question || 'Trivia Question'}`, 50, triviaY, { width: 512 });

          triviaY = doc.y + 6;

          // Render options list
          if (round.options && round.options.length > 0) {
            doc.fillColor('#475569')
               .font('Helvetica')
               .fontSize(9);

            // Print options list
            const optText = round.options.join('    •    ');
            doc.text(`Options:   •   ${optText}`, 65, triviaY, { width: 497 });
            triviaY = doc.y + 4;
          }

          // Correct response highlight
          doc.fillColor('#4F46E5')
             .font('Helvetica-Bold')
             .fontSize(9.5)
             .text(`Correct Option:   [ ${round.answer || 'N/A'} ]`, 65, triviaY);

          triviaY = doc.y + 18;
        });
      }

      // Conclude document stream
      doc.end();

    } catch (err) {
      reject(err);
    }
  });
}
